### ISSUE TITLE
Error trying to compile(SO - Windows 64-bit)

### ISSUE THREAD

**Issue by clovis-rosa** [VladimirMikulic/parcel-plugin-custom-dist-structure#1]
H! Vladmir, thank you very much for put your time on it!
I'm running a simple HTML, CSS and Js project on VSCode. It runs with no erros without the plugin, but once I try to run it after install the plugin the following error pops up:

`Server running at http://localhost:1234 
√  Built in 949ms.
×  Path contains invalid characters: C:\landingpage_test\dist\css\C:\landingpage_test\dist
    at checkPath (C:\landingpage_test\node_modules\make-dir\index.js:16:18)
    at AsyncFunction.module.exports.sync (C:\landingpage_test\node_modules\make-dir\index.js:108:2)
    at AsyncFunction.module.exports.sync (C:\landingpage_test\node_modules\move-file\index.js:58:10)
    at moveFileSync (C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\Utils.js:33:12)
    at FileProcessor.processFile (C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\FileProcessor.js:24:5)
    at C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\OutputGenerator.js:47:21
    at Array.forEach (<anonymous>)
    at OutputGenerator.processFiles (C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\OutputGenerator.js:39:11)
    at C:\landingpage_test\node_modules\parcel-plugin-custom-dist-structure\lib\OutputGenerator.js:34:12
    at Array.forEach (<anonymous>)
`

Here is my JSON file: 

`{
  "name": "landingpage_test",
  "version": "1.0.0",
  "description": "Test project using 'parcel-plugin-custom-dist-structure' for ParcelJs.",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "scripts": {
    "clean": "rm dist/bundle.js",
    "start": "parcel src/index.html",
    "build-prod": "parcel build src/index.html"
  },
  "customDistStructure": {
    "config": {
      ".css": "css",
      ".js": "js",
      "images": [
        ".jpg",
        ".svg",
        ".png"
      ]
    },
    "options": {
      "development": true
    }
  },
  "dependencies": {},
  "devDependencies": {
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-custom-dist-structure": "^1.0.2"
  }
}`

You can find the whole project in my GitHub: _https://github.com/clovis-rosa/landingpage_test_
Cheers!

**Comment by VladimirMikulic** [comment]
Hi @clovis-rosa! Thank you very much for reporting the issue with such a detailed description!
I am working on the fix! It should arrive soon.

**Comment by VladimirMikulic** [comment]
The issue has been fixed! You can download the new version `1.0.3` to confirm that it works.
Again, thank you for reporting this critical issue :+1:

**Comment by clovis-rosa** [comment]
Thank you @VladimirMikulic, it's working!
I've just opened another issue related to SCSS files. 

All the best and stay safe!

**Comment by VladimirMikulic** [comment]
@clovis-rosa this time I was faster and I've fixed it before you had opened it :)
Run `npm update` to go from `1.0.3` to `1.0.4`.

Enjoy it :rocket:
