### ISSUE TITLE
Error when putting in css images

### ISSUE THREAD

**Issue by klimnikova** [VladimirMikulic/parcel-plugin-custom-dist-structure#12]
Hi!
Thnx for nice package!
I want to implement the next structure:
```
"customDistStructure": {
    "config": {
      ".css": ["css", ".jpg", ".png"],
      ".css.map": "css",
      ".js.map": "js",
      ".js": "js"
    },
    "options": {
      "development": false
    }
  }
```
But I get the error :  sanitizedFolderName.startsWith is not a function.

**Comment by VladimirMikulic** [comment]
Hi and you are welcome :)

The first line of your config object is not valid. If the key starts with `.` it is treated as a file type. The expected value is folder where it should place `.`files.

If you want your images and css to be in the same folder, this is your key-value pair:
"css": [.css, .jpg, .png] -> translates to " Put all css files and images in the css folder.

I hope that now you understans why your first line wouldn't work.
