### ISSUE TITLE
Integration with parcel-plugin-compress

### ISSUE THREAD

**Issue by IsaacHub** [VladimirMikulic/parcel-plugin-custom-dist-structure#13]
I use `parcel-plugin-compress` to produce compressed files `scripts.js` to `scripts.js.br` and `scripts.js.gz`, it works well, but I wanted them to be structured like following:
```
dist/
   js/
     scripts.js
     scripts.js.br
     scripts.js.gz
```

While I build, those two compressed files are missing, If I remove this plugin and rebuild then I got those files back but I don't want a flat directory structure.

My `package.json` config:

```
"customDistStructure": {
    "config": {
      "js": [ ".js",".js.map",".js.br",".js.gz" ],
      "css": [ ".css", ".css.map", ".css.br",".css.gz" ]
    },
    "options": {
      "development": true
    }
  }
```

**Comment by VladimirMikulic** [comment]
Hi @IsaacHub.

Thank you for reporting this.
Your `.br/.gz` files are not deleted, in fact they were never generated :)

My plugin runs before `parcel-plugin-compress` and moves files into their respective folders.
When `parcel-plugin-compress` runs, it looks for files in the root of the `dist` folder, but since my plugin has already moved them, `parcel-plugin-compress` can't generate compressed files.

I'll see if something can be done about it.

**Comment by VladimirMikulic** [comment]
I've filed an [issue](https://github.com/parcel-bundler/parcel/issues/4516) to Parcel developers to see if it's possible to make my plugin run last.

**Comment by VladimirMikulic** [comment]
Unfortunately, due to Parcel's architecture, this is not possible.
The workaround could be to make `postbuild` script and use another NPM package to GZIP the the build files.

**Comment by IsaacHub** [comment]
This doesn't make any sense, I filed an issue that your plugin deletes files with extension `.br` and `.gz`, This has nothing to do with `parcel-plugin-compress`, That plugin's job is to make `.gz` files, your plugin's job is to move them to a specified directory. 

Your plugin deletes `.js.gz` files instead of moving. what this has to do with order of execution or async/sync operations? **If `*.js.map` can be moved then why not `*.js.gz`?**

**Comment by ralscha** [comment]
The `parcel-plugin-compress` receives the files it has to compress from Parcel via the `bundle` object. Is there a way for the `parcel-plugin-custom-dist-structure` to amend this structure?
If that is not possible I will look for another solution. 

Here the code from `parcel-plugin-compress` that compresses the files
```js
module.exports = bundler => {
  bundler.on('bundled', async (bundle) => {
    function* filesToCompress(bundle) {
      if (bundle.name && fileTest.test(bundle.name)) {
        yield bundle.name
      }
      for (var child of bundle.childBundles) {
        yield* filesToCompress(child)
      }
    }
    [...filesToCompress(bundle)].forEach(file => {
```

The bundle object looks like this
```
{
  type: 'html',
  name: 'c:\\temp\\compress\\dist\\index.html',
  childBundles: [{
      type: 'js',
      name: 'c:\\temp\\compress\\dist\\src.67e05423.js',
      ....
  }],
```

**Comment by IsaacHub** [comment]
I already figured it out, and done it https://github.com/ralscha/parcel-plugin-compress/issues/10#issuecomment-618164700

I moved that `parcel-plugin-compress` folder out of `node_modules` and referring from local root path and modified `package.json` to point to that modified local plugin directory path.

**Comment by VladimirMikulic** [comment]
@ralscha thank you very much for your willingness to help, but we both as developers can't do anything about this. Unfortunately, your solution wouldn't work. Even if I modify the `bundle` object, your plugin has already received the original Parcel's `bundle` object. (async operations, remember 
 :)
Not to mention side effects that it can have for other plugins that user might have.

Personally, I think it would be best for users who want to compress their files is to include `postbuild` script and they could use your `bread-compressor-cli` for compression.

@IsaacHub calm down. I've read your deleted comment. Stop jellying!
I've nicely explained to you why it doesn't work the way you think is perfect.
This is OSS and it's not nice of you to behave like a brat to people trying to help you and figure out the best possible solution.

**Comment by IsaacHub** [comment]
@VladimirMikulic At first I read your last comment and later I realized there were 3 comments, and then I read your first comment and realized that those files were not generated at all. That's what the cause of my confusion, sorry.

Anyway, I patched a reliable solution to `compress` plugin.
