### ISSUE TITLE
Dynamic import throws error in production mode, but works in dev mode

### ISSUE THREAD

**Issue by IsaacHub** [VladimirMikulic/parcel-plugin-custom-dist-structure#15]
I downloaded https://github.com/finmavis/parcel-boilerplate

I installed this plugin and `parcel src/index.html` then it works:

![Screenshot_27](https://user-images.githubusercontent.com/20126441/80128308-18352e00-85b3-11ea-945a-01e27a957e6d.png)

But if I build using `parcel build` and use a local static server https://www.npmjs.com/package/serve
`serve`
then dynamic import won't work:  https://github.com/finmavis/parcel-boilerplate/blob/f175aee14830348538ff4295bc8a70038e0f660b/src/index.js#L6

![Screenshot_26](https://user-images.githubusercontent.com/20126441/80128582-81b53c80-85b3-11ea-9b93-c69fcb1ed6df.png)

**If I remove this plugin's config from package,json and rebuild it again then this error is not present and working as expected.**

**Comment by VladimirMikulic** [comment]
Dynamic imports work fine.

You might be missing:

1) 
```json
  "browserslist": [
    "last 1 Chrome versions"
  ]
```

2) **--public-url=./** in Parcel's build command.
