### ISSUE TITLE
Plugin parcel-plugin-custom-dist-structure failed to initialize: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string.

### ISSUE THREAD

**Issue by oberonlai** [VladimirMikulic/parcel-plugin-custom-dist-structure#16]
Hi Vladimir~

I updated to version 1.1.9 and got the following error message:

`Server running at http://localhost:1234 
⚠️  Plugin parcel-plugin-custom-dist-structure failed to initialize: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Module.require (internal/modules/cjs/loader.js:685:3)
    at require (/Users/oberonlai/Sites/Hellowp/wp-content/themes/ods/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/oberonlai/Sites/Hellowp/wp-content/themes/ods/node_modules/parcel-plugin-custom-dist-structure/lib/index.js:8:19)
    at Module._compile (/Users/oberonlai/Sites/Hellowp/wp-content/themes/ods/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)`

It worked normally unless I removed the package-lock.json and reinstall the version 1.1.2. Could you help me to figure out what's happened? Thanks for help!

**Comment by VladimirMikulic** [comment]
Hi @oberonlai.
Of course, I can. Did you run `parcel <entryFile>` as a NPM script or from terminal.
If you've run it from terminal (that means that you have parcel globally installed) you need to run `npm link parcel-bundler` to put globally installed package into your projects `node_modules` folder.

Let me know if this works.

Thank you.

**Comment by oberonlai** [comment]
Thanks! Run npm link parcel-bundler is works! 

I run parcel in NPM script, do I run npm link parcel-builder everytime in my future project? Is there any methods to fix the problem at one time?

**Comment by julienfastre** [comment]
I encounter the same problem with parcel installed locally (in `node_modules`) :unamused: 

```
ode@f720602bf34b:/app$ npm --version
6.13.4
node@f720602bf34b:/app$ node --version
v12.16.1
```
package.json:

```json
{
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^2.1.2",
    "autoprefixer": "^9.7.6",
    "parcel": "^1.12.4",
    "tailwindcss": "^1.3.5"
  },
  "dependencies": {
    "clipboard": "^2.0.6",
    "parcel-plugin-custom-dist-structure": "^1.1.9",
    "sass": "^1.26.5"
  },
  "customDistStructure": {
    "config": {
      "static": [
        ".css",
        ".eot",
        ".js",
        ".map",
        ".otf",
        ".png",
        ".jpeg",
        ".jpg",
        ".svg",
        ".ttf",
        ".woff2",
        ".woff"
      ]
    },
    "options": {
      "development": true
    }
  }
}
```

**Comment by VladimirMikulic** [comment]
Hi @julienfastre. Thank you for your detailed package.json file.
The right package is `parcel-bundler`, not `parcel` :)

@oberonlai at the moment if you run parcel from the terminal like:
`> parcel <entryFile>` it is mandatory to run `npm link parcel-bundler`.
If you are running parcel in NPM script, this is not required.

The version v1.1.9 includes improvements about CSS reload (HRM server).
I am using Parcel internals, so that's why `parcel-bundler` needs to be present project's `node_modules` folder. 

Currently, I am exploring possibilities which would allow me to use HMR server without `parcel-bundler` present in the project's `node_modules` folder.

**Comment by oberonlai** [comment]
I installed the parcel not parcel-bundler, too. I have switched to the parcel-bundler and problem being solved. Thanks~

**Comment by VladimirMikulic** [comment]
@oberonlai I am glad to hear it's working!
