### ISSUE TITLE
Parcel v2 support?

### ISSUE THREAD

**Issue by duncanhall** [VladimirMikulic/parcel-plugin-custom-dist-structure#2]
Hey @VladimirMikulic  thanks for your work on this.

Are you able to confirm if this plugin works with parcel v2? I've installed the plugin and added a `customDistStructure` to my `package.json` but there are no changes to my output structure.

I am running parcel version `2.0.0-alpha.3.2`.

**Comment by VladimirMikulic** [comment]
Hi @duncanhall! Version 2 is supported. I am running the same Parcel version as you.

```jsonc
  "customDistStructure": {
    "config": {
      ".css": "css",
      ".js": "js",
      "images": [
        ".jpg",
        ".svg",
        ".png"
      ]
    }
  },
  "devDependencies": {
    "parcel": "^2.0.0-alpha.3.2",
    "parcel-plugin-custom-dist-structure": "^1.0.4"
  },
```
Please provide your config object and I'll be happy to help you.

**Comment by VladimirMikulic** [comment]
I could add support for the v2, but it would be a completely different package/repo.

**Comment by bySabi** [comment]
@VladimirMikulic  please create a different branch, maybe v2?, for Parcel v2 support.

**Comment by VladimirMikulic** [comment]
Hi @bySabi. I appreciate your vote on this topic.
A few days ago Parcel 2 beta 1 has been released and it's time to start working :)
