### ISSUE TITLE
Ignore some files

### ISSUE THREAD

**Issue by pukarsharma112** [VladimirMikulic/parcel-plugin-custom-dist-structure#28]
Is there any way to ignore some files .. ie: favicon.png and apple-touch-icon.png, service-worker.js etc but put other similar files as structured??

**Comment by VladimirMikulic** [comment]
Hi @pukarsharma112.
First of all, you need to know that Parcel bundles all files referenced by `index` file that you specify (its dependencies) and they are outputted in the root of the `dist` folder.
If I understand you correctly, you would like to keep `favicon.png, apple-touch-icon.png, service-worker.js` in the root of the dist folder, right?

**Comment by pukarsharma112** [comment]
yes, i understand that parcel by default put all files in dist folder so i used your plugin to structure the dist folder. But i want to ignore some files like mentioned above so that they will always be on root folder...

**Comment by VladimirMikulic** [comment]
@pukarsharma112 sorry for a late reply. Currently, it is not possible to ignore specific files. By any chance, could [this](https://www.npmjs.com/package/parcel-plugin-static-files-copy) plugin provide the functionality you desire?

**Comment by pukarsharma112** [comment]
thanks for your suggestion but that plugin don't provide what i want. Anyway your plugin is still helping me :-)

**Comment by VladimirMikulic** [comment]
I appreciate your kind words @pukarsharma112. I have some plans to improve this plugin and I'll make sure to include this feature as well :)

**Comment by pukarsharma112** [comment]
Thank you sir. But anyway the plugin is so well to manage the
output structure rather than just putting all files in same directory. And
one issue i have found is when i add manifest.webmanifest file and images,
then the images are placed in the directory as specified in config but
those images path on .webmanifest file are not updated

**Comment by VladimirMikulic** [comment]
`.webmanifest` file doesn't ring the bell. What type of project are you working on?

**Comment by pukarsharma112** [comment]
pwa requires manifest.json but with parcel, we need to use
manifest.webmanifest

**Comment by VladimirMikulic** [comment]
Thanks for the clarification. This plugin updates path of files that are present in the graph which the plugin receives from Parcel.
If `manifest.webmanifest` is not in the graph, then it won't modify it. Could you possibly set up an example project so I can take a look and see what's going on? Thanks.

**Comment by pukarsharma112** [comment]
Here's my basic project structure
https://github.com/pukarsharma112/plugin-test.git
I have also uploaded dist directory, check the manifest.webmanifest file
and see those `icons.src` url

**Comment by VladimirMikulic** [comment]
Thank you for this @pukarsharma112. This is plugin's issue which I've identified and I am working on the fix!

**Comment by pukarsharma112** [comment]
you're welcome sir. I am happy and satisfied to use your plugin.

**Comment by pukarsharma112** [comment]
actually there is a way to solve the issue that i opened on github. your
plugin checks extension and put the builds to directory based on those
extensions. but if there is any

**Comment by pukarsharma112** [comment]
actually there is a way to solve the issue that i opened on github. your
plugin checks extension and put the builds to directory based on those
extensions. but if there is any way so that the plugin first checks if it
is filename or extension and then output the build files based on the
config. I don't know if this is really possible or not but i just want to
share the idea. but anyway your plugin had helped me to make my dist folder
structured and clean rather than the way parcel flatten all the files to a
same folder. 🙂🙂

**Comment by VladimirMikulic** [comment]
@pukarsharma112 you are reading my mind. That's exactly what I thought. You could specify an array containing Regex expressions which describe which files plugin should ignore/keep in the root of the dist folder. 

By the way, I've fixed the issue with the manifest, checkout newest version 1.1.14.
Enjoy and stay tuned for additional updates :)

Lastly, I would like to thank you for your help and for reporting these issues which need to be addressed.

PS. Please, don't call me "sir". Don't hesitate to comment and express your opinion. After all, we are software developers not military commanders :)
