### ISSUE TITLE
Request information about readme enclosed image

### ISSUE THREAD

**Issue by eclisia** [VladimirMikulic/parcel-plugin-custom-dist-structure#33]
Dear, I found  your readme following a post on Dev.to
That's true your readme is very nice : great !
But I wonder how you added the image (cloud, package, etc.) in your readme ?
The only way I know are : 
1 - commit an image in the repo, then call it with markdown syntax,
2 - call an image from Internet.
But, in your case, it seems you use 
`## :code: your title`

**Comment by VladimirMikulic** [comment]
Hi @eclisia!

"Cloud", "package" etc. are not images actually. They are emojis.
Github supports special `:emoji:` syntax so when Github encounters it, 
Github replaces `:emoji:` with a corresponding emoji.

Hopefully, this clears your doubt.

**Comment by eclisia** [comment]
So obvious...  :disappointed: Thanks a lot !

**Comment by eclisia** [comment]
So obvious...  :disappointed: Thanks a lot !

**Comment by VladimirMikulic** [comment]
@eclisia no problem! Glad it was helpful!
