### ISSUE TITLE
The plugin doesn't work for me

### ISSUE THREAD

**Issue by AndreaBaccolini** [VladimirMikulic/parcel-plugin-custom-dist-structure#34]
Hi, it's just the plugin I was looking for for me that I make sites but unfortunately I can't get it to work.
It does not create folders in the "dist" directory
This is my Package.json

<pre>
`{
  "name": "provaparcel2",
  "version": "1.0.0",
  "dependencies": {
    "parcel": "^2.0.0-beta.1",
    "sass": "^1.26.10"
  },
  "devDependencies": {
    "autoprefixer": "^9.8.6",
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-clean-easy": "^1.0.2",
    "parcel-plugin-custom-dist-structure": "^1.1.14",
  },
  "scripts": {
    "start": "parcel serve index.html",
    "build": "parcel build index.html --public-url ./"
  },
  "keywords": [],
  "author": "Andrea Baccolini",
  "license": "ISC",
  "description": "",
  "parcelCleanPaths": [
    "dist"
  ],
  " customDistStructure ": {
    " config ": {
      " .css ": " css ",
      " .js ": " js ",
      " images ": [
        " .jpg ",
        " .svg ",
        " .png "
      ],
      ".fileExtension": "folder/in/dist",
      "folder/in/dist": [ ".file", ".extensions" ]
    },
    "options": {
      "development": true
  }
}}
</pre>

**Comment by VladimirMikulic** [comment]
Hi @AndreaBaccolini.
You are using Parcel version 2. There are architectural differences between Parcel v1 and v2.
At the moment this plugin supports only Parcel v1.

**Comment by AndreaBaccolini** [comment]
It doesn't even work with PArcel v1.12.4
<pre>
{
  "name": "provaparcel2",
  "version": "1.0.0",
  "dependencies": {
    "parcel": "^2.0.0-beta.1",
    "sass": "^1.26.10"
  },
  "devDependencies": {
    "autoprefixer": "^9.8.6",
    "parcel": "1.12.4",
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-clean-easy": "^1.0.2",
    "parcel-plugin-custom-dist-structure": "^1.1.14",
    "sass": "^1.26.10"
  },
  "scripts": {
    "start": "parcel serve index.html",
    "build": "parcel build index.html --public-url ./"
  },
  "keywords": [],
  "author": "Andrea Baccolini",
  "license": "ISC",
  "description": "",
  "parcelCleanPaths": [
    "dist"
  ],
  " customDistStructure ": {
    " config ": {
      " .css ": " css ",
      " .js ": " js ",
      " images ": [
        " .jpg ",
        " .svg ",
        " .png "
      ],
      ".fileExtension": "folder/in/dist",
      "folder/in/dist": [ ".file", ".extensions" ]
    },
    "options": {
      "development": true
  }
}}

</pre>

**Comment by VladimirMikulic** [comment]
@AndreaBaccolini plugin does work but your config on the other hand... :)

First of all, you have spaces surrounding keys in package.json which is not standard.
`" customDistStructure "` -> `"customDistStructure"`

You could also potentially have conflicting dependencies since you have 3 Parcel packages installed.
Parcel v2, and Parcel v1 (`parcel` & `parcel-bundler`).

Also, what is your OS?

**Comment by AndreaBaccolini** [comment]
Ok thx now work
