### ISSUE TITLE
Merge with parcel-plugin-structurize

### ISSUE THREAD

**Issue by samrith-s** [VladimirMikulic/parcel-plugin-custom-dist-structure#35]
Hey guys 👋 ,

I see this project does exactly (almost) what a plugin of mine, [parcel-plugin-structurize](https://github.com/samrith-s/parcel-plugin-structurize), does. 

I was wondering if we could merge the two into a new plugin? Also wanter to understand what types of input does this plugin supports, etc etc.

Cheers!

**Comment by VladimirMikulic** [comment]
Hi @samrith-s!
There is no us, it's only me haha :)

Why would you like to merge them? Isn't that too much of a hassle?

>  Also wanted to understand what types of input does this plugin supports, etc etc.

The plugin supports just about anything. You simply specify a file extension and the path where you would like it to be stored.

**Comment by samrith-s** [comment]
Ah got it haha! Okay, I was wondering how you support and update paths in the HTML (or other input) files?

Also the point of merging was so that we can maintain one project and provide better coverage and support. 😄

**Comment by VladimirMikulic** [comment]
Hi @samrith-s.

I truly appreciate the offer but our projects are different, not only in technical implementation but in functionality as well.
Regarding the path updates, it's fairly complex. I would need to write a blog post about it  :)

**Comment by samrith-s** [comment]
Ah gotcha. No problem. :) 

I just did a big rewrite of my entire plugin and figured out the pathing thing. Thanks again!
