### ISSUE TITLE
Puts css in folder but does not link to it

### ISSUE THREAD

**Issue by pstema** [VladimirMikulic/parcel-plugin-custom-dist-structure#36]
**Describe the bug**
Thank your for this cool plug i!

adds a css directory but this breaks the link to the css
the image, js are generated as expected

<link rel="stylesheet" href="app.c328ef1a.css">
should be
<link rel="stylesheet" href="css/app.c328ef1a.css">

**How it happened?**
make dir for css, js, images

**Desktop (please complete the following information):**
 - OS: Windows
"parcel-bundler": "^1.12.4",
 "parcel-plugin-custom-dist-structure": "^1.1.16",

**Plugin configuration object:**
"customDistStructure": {
    "config": {
      ".css": "css",
      ".css.map": "css",
      ".js": "js",
      ".js.map": "js",
      "images": [
        ".jpg",
        ".png",
        ".gif",
        ".jpeg"
      ],
      ".fileExtension": "folder/in/dist",
      "folder/in/dist": [ ".file", ".extensions" ]
    },
    "options": {
      "development": true
    }
  }

Thank you
Peter

**Comment by VladimirMikulic** [comment]
Hi @pstema! Thanks for reporting this issue. Unfortunately, I am not sure if I would have time to take a detailed look at it :(

**Comment by VladimirMikulic** [comment]
Hi @pstema. v.1.1.17 has been released. I've tested it with a similar repo and the issue should be resolved for you too!
