### ISSUE TITLE
Does it works for parcel version 2?

### ISSUE THREAD

**Issue by Panbehkar** [VladimirMikulic/parcel-plugin-custom-dist-structure#37]
It was working with `parcel-bundler` (version 1).
I removed the parcel-bundler, and install `parcel `(version 2).
I didn't change any other config in my `package.json`, but it doesn't work now!
Now when I `build`, I don't have the `files` folder inside `dist`, only the `dist ` folder is exist
```
"customDistStructure": {
  "config": {
    "files": [
      ".css",
      ".js",
      ".woff",
      ".png",
      ".jpg"
    ]
  }
}
```

**Comment by VladimirMikulic** [comment]
Hello @Panbehkar. The version 2 is currently not supported.

**Comment by Panbehkar** [comment]
Thank you so much.
Is there another package or method I can use for this purpose (in version 2)?

**Comment by VladimirMikulic** [comment]
Hello @Panbehkar. I am not aware of solutions for Parcel 2. Thanks.

**Comment by julianxhokaxhiu** [comment]
Is there any plan to migrate to v2 eventually?

**Comment by VladimirMikulic** [comment]
@julianxhokaxhiu no plans at the moment. Sorry!

**Comment by Jako** [comment]
> Thank you so much.
> Is there another package or method I can use for this purpose (in version 2)?

You can use `parcel-namer-rewrite` with this example configuration: https://github.com/ol-loginov/parcel-namer-rewrite/issues/6#issue-992916247

**Comment by adrian5** [comment]
@VladimirMikulic Could you add a brief note to the README about Parcel 2 not being supported? I suspect most users landing here will be using that by now. Thanks!

**Comment by VladimirMikulic** [comment]
@adrian5 done! Thanks for the reminder!
