### ISSUE TITLE
How to save svg fonts to the fonts folder?

### ISSUE THREAD

**Issue by double-trouble2** [VladimirMikulic/parcel-plugin-custom-dist-structure#38]
Hi first thank you for such a cool plugin. There was a need to save fonts, in this configuration all fonts are saved except for vector fonts. How to exclude svg files from images?
`"customDistStructure": {
    "config": {
      ".css": "css",
      ".js": "js",
      "images": [
        ".jpg",
        ".svg",
        ".png"
      ],
      ".eot": "fonts",
      ".ttf": "fonts",
      ".woff": "fonts",
      ".woff2": "fonts",
      "fonts": [ ".Montserrat-Light", ".svg" ],
      "fonts": [ ".Montserrat-Regular", ".svg" ]
  },
  "options": {
    "development": true
  }
  }`

**Comment by VladimirMikulic** [comment]
Hello @double-trouble2.
I appreciate your kind words.

If I understood your problem, this should work for you:
```json
{
   "config":{
      ".css":"css",
      ".js":"js",
      "images":[
         ".jpg",
         ".svg",
         ".png"
      ],
      "fonts":[
         ".eot",
         ".ttf",
         ".woff"
         ".woff2"
         ".Montserrat-Light"
         ".Montserrat-Regular"
      ]
   },
   "options":{
      "development":true
   }
}
```

**Comment by double-trouble2** [comment]
I'm very glad you responded so quickly @VladimirMikulic . I'm sorry I didn't state the problem correctly. I need to leave svg images in the **images** folder and svg fonts in **fonts**. And with this configuration svg fonts are generated in the **dist** folder.

**Comment by VladimirMikulic** [comment]
Hello @double-trouble2. It's alright. I've edited my previous comment/config. Does it work for you now? Thanks.

**Comment by double-trouble2** [comment]
Hello @VladimirMikulic .
No it didn't work (
![image](https://user-images.githubusercontent.com/16848648/99918791-18f59480-2d3b-11eb-8427-d09b633f840d.png)

**Comment by VladimirMikulic** [comment]
@double-trouble2 I am sorry to hear that. This is a bug then :(

**Comment by double-trouble2** [comment]
@VladimirMikulic  Well, we'll wait for the new version. I also subscribed to you on Twitter. Good luck!

**Comment by VladimirMikulic** [comment]
Hi @double-trouble2. v1.1.17 has been released. It solved many issues and I hope it solved this one for you too!
Closing this now but feel free to reopen if it does occur again!
