### ISSUE TITLE
The plugin "parcel-plugin-custom-dist-structure" has encountered an error. 

### ISSUE THREAD

**Issue by double-trouble2** [VladimirMikulic/parcel-plugin-custom-dist-structure#39]
`  "customDistStructure": { `
`    "config": {`
 `     ".css": "css",`
 `     ".js": "js",`
`      "fonts": [`
  `      ".eot",
   `     ".ttf",
    `    ".woff",
     `   ".woff2"
      `],`
`      "images": [`
 `       ".jpg",`
  `      ".svg",`
   `     ".png",`
    `    ".webp"`
     ` ],`
      `"images/**": [`
`        ".jpg",`
 `       ".svg",`
  `      ".png",`
   `     ".webp"`
`      ]`
 `   },`
`    "options": {`
`      "development": false`
`    }`
`  },`
Oh, snap!
 The plugin "parcel-plugin-custom-dist-structure" has encountered an error. ⚠️
  
 We apologize for inconvinience. 💖

 TypeError: Cannot read property 'distribute' of undefined
    at SVGSpriterQueue.remove (/media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/lib/svg-sprite/queue.js:97:58)
    at /media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/node_modules/async/dist/async.js:473:16
    at next (/media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/node_modules/async/dist/async.js:5329:29)
    at /media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/node_modules/async/dist/async.js:969:16
    at /media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/lib/svg-sprite.js:200:9
    at /media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/node_modules/async/dist/async.js:473:16
    at next (/media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/node_modules/async/dist/async.js:5329:29)
    at /media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/node_modules/async/dist/async.js:969:16
    at /media/islombek/84732b38-d372-4283-aab7-550172b13b8a/islombek/Projects/tailwind-parcel/node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js:95:9

**Comment by VladimirMikulic** [comment]
Hello @double-trouble2. `images/**` is not supported. Use `images/folder` instead.

**Comment by double-trouble2** [comment]
> Hello @double-trouble2. `images/**` is not supported. Use `images/folder` instead.

Ah, got it. and you don't know how to set up the building svg sprites in parcel? I'll be very thankful.

**Comment by VladimirMikulic** [comment]
@double-trouble2 check out `parcel-plugin-svg-sprite`.
