### ISSUE TITLE
Wrong file path links in development mode - HTML files

### ISSUE THREAD

**Issue by clovis-rosa** [VladimirMikulic/parcel-plugin-custom-dist-structure#4]
Hey @VladimirMikulic. Hope you're keeping well!

As you can see in the example above, it's loosing the correct path "/css/", "/js/" and "/images/" in the compiled HTML(dist folder) file, BUT it only happens when the HTML(src folder) is modified.

Again, while i'm working on the SCSS file and saving, everything works fine. Once I change anything in the HTML, it breaks!
I haven't test anything with JS files at this point, so if you can run some tests...

`<link rel="stylesheet" href="/styles.164d45a1.css">`
`<script src="/styles.164d45a1.js"></script>`
`<img src="/illustration-office.db97d6a7.png" alt="">`

Thank you!

**Comment by VladimirMikulic** [comment]
Thank you @clovis-rosa for all the testing you did :+1: 
I apologise for the bugs in development mode, patches will land soon.

**Comment by m615926** [comment]
Thanks for great plugin and I finally can use Parcel in production site. I have the same issue and I see your latest version 1.0.5 seems to fix it. I have tried it and worked perfectly.

But I found it can't reload automatically when I modified any files. I have to refresh manually. Is it the Parcel or your plugin problem? I can't figure out. Could you try it?

**Comment by m615926** [comment]
@VladimirMikulic Thanks for great plugin and I finally can use Parcel in the production site. But I also have same issue, looking forward your patches. Thanks a lot!

**Comment by VladimirMikulic** [comment]
Hi @m615926. I am pleased to hear that you are satisfied. At the moment development mode is unstable, but I am working on it!

**Comment by VladimirMikulic** [comment]
This is related to #3 as well.

**Comment by VladimirMikulic** [comment]
@m615926 @clovis-rosa it took me very long 3 days to fix the development mode, but I think that I finally got it. Before publishing the new version to the NPM, I would be thankful to you both if you could try it?

1. Clone the project `git clone https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure.git`
2. Check out the test branch `git checkout fix/development-mode`
3. Make it available globally on your system `npm link`
4. After running `npm link`, you'll get the absolute path to the package -> copy it
5. Enter your project and run `npm i -D <absolute_path>` to install the plugin
6. Report the results here

Thank you for your patience.

**Comment by m615926** [comment]
You Rock!!! It's so appreciate your effort!

I followed you steps and I got the following error message. Did I paste the wrong path?

![CleanShot 2020-03-26 at 10 49 13](https://user-images.githubusercontent.com/1587136/77605291-7f79a700-6f4f-11ea-9ac7-9d1dba7d0b0c.jpg)

**Comment by VladimirMikulic** [comment]
@m615926 thank you. I think you've misunderstood the step 5.
You are still in the plugin folder, that's why you get this error. You should enter another project that you are working on and install it there.

Let me know if it helps and I appreciate your effort :+1:

**Comment by m615926** [comment]
I got it and have tried again, there was a new error "Node does not exist: /Users/oberonlai/Sites/Hellowp/wp-content/themes/ods/assets/.DS_Store". I didn't get what it means? Do I have the wrong config with your plugin? And I still get same issue when I update my index.pug file. 😭 

![CleanShot 2020-03-27 at 11 04 24](https://user-images.githubusercontent.com/1587136/77717182-c1bbea80-701a-11ea-9138-0b6f0e52fa80.jpg)
![CleanShot 2020-03-27 at 11 05 04](https://user-images.githubusercontent.com/1587136/77717241-e87a2100-701a-11ea-824f-415ad8c641df.jpg)

**Comment by VladimirMikulic** [comment]
Hi @m615926.
Thank you very much on these screenshots! This an expected behaviour.
Currently, the plugin does not support multiple entry files i.e `src/*.pug`.
That's why it fails. If you could try it out it with only one entry file I would be very thankful.

After this gets resolved I'll start working on #6 (Multiple entries support), no worries :)

**Comment by m615926** [comment]
Thanks! I used to separate the multiple folder to manage the files, and that's reason why I couldn't use Parcel in my project now. Looking forward your update, I can't wait to use your plugin!!!

**Comment by VladimirMikulic** [comment]
Wow, I appreciate your kind words :+1: 
The development continues :factory: 
So, does it work for you with a single entry file? I've tested it locally with a few configs and didn't found any problems which is awesome!

**Comment by m615926** [comment]
😢 

![CleanShot 2020-03-27 at 11 24 39](https://user-images.githubusercontent.com/1587136/77718359-b4542f80-701d-11ea-940f-2b0cc6d61324.jpg)

**Comment by VladimirMikulic** [comment]
Do you maybe have .DS_Store in your projects folder or src? It might have included it wrongly.

**Comment by oberonlai** [comment]
No, how can I generate the .DS_Store file?

**Comment by VladimirMikulic** [comment]
Finder creates it automatically to store some metadata about the folder.
This is a very good catch, I'll release the fix in the next few minutes...

**Comment by VladimirMikulic** [comment]
@oberonlai could you try it now? Sorry, it took me a bit of time to fix this. The tests were updated as well, so this won't happen again :)

**Comment by oberonlai** [comment]
You are awesome! Missing .DS_Dtore file is fixed. But I still can't use the multiple entries. It's so close~

![CleanShot 2020-03-27 at 15 12 45](https://user-images.githubusercontent.com/1587136/77731222-78c95d80-703d-11ea-882d-4d5e87d43350.jpg)

**Comment by VladimirMikulic** [comment]
@oberonlai that's awesome news. It means that we've finally fixed the development mode :tada: 
Thank you very much for your help. Don't worry for multiple entries, I am already working on the feature ;)
