### ISSUE TITLE
Websocket is not open - Error

### ISSUE THREAD

**Issue by ashehzadgec** [VladimirMikulic/parcel-plugin-custom-dist-structure#40]
Hi 

I was using parcel bundler with your awesome plugin and suddenly got this attached error. I am not a backend guy and did not understood this error. Can u pls tell me what caused this error and what is it?

Note: My system was idle for like 90 mnts just for info. I may be related to the problem so I am sharing.
![Screenshot 2021-02-19 141722](https://user-images.githubusercontent.com/65112198/108484034-38aa4380-72bd-11eb-9f32-01bbbdfac0ba.png)

Regards,
Shehzad Asif
Front End Developer

**Comment by VladimirMikulic** [comment]
Thanks, @ashehzadgec. This can sometimes happen, so be sure to just restart the process and you should be good to go :+1:

**Comment by ashehzadgec** [comment]
Welcome,

Good to know that nothing to worry about.
