### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by chellios-byte** [VladimirMikulic/parcel-plugin-custom-dist-structure#44]
Hi! My name is Andrew, I'm new to front-end development, in my projects I use parcel,  and tried using your npm package , custo-dist and can't figure to make it work, simply i dont know to configure it and to start using it in my projects.
   
   If you cand guide me in configure it , i'll apreciate your time and effort!

         Best wishes,
                    Andrew

[package json.zip](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure/files/6429651/package.json.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Parcel version: [1.12.5]
 - Plugin version: [e.g. v1.1.17]

**Plugin configuration object:**
Your `customDistStructure` key in package.json.
![package-json](https://user-images.githubusercontent.com/68940868/117195345-d8bc3700-aded-11eb-81f1-c898296594f4.jpg)

**Comment by VladimirMikulic** [comment]
Hi Andrew. It seems that your JSON is missing a certain character, but I can't tell which one is it. Sorry!

**Comment by chellios-byte** [comment]
Thank you!
