### ISSUE TITLE
[Suggestion] Join forces with 'structurize' and 'parcel-namer-rewrite'

### ISSUE THREAD

**Issue by iocouto** [VladimirMikulic/parcel-plugin-custom-dist-structure#46]
It may be worthwhile getting in touch with a couple of other developers that are trying to develop Parcel plugins to solve the same problem as 'parcel-plugin-custom-dist-structure'. Perhaps you could all join forces and put together a single 'custom-dist-dir' plugin - which might make the job of maintaining and upgrading the plugin easier for you all. 

There are a couple of projects I know of which are similar to 'parcel-plugin-custom-dist-structure', and which seem to be actively maintained:

- [parcel-namer-rewrite](https://github.com/ol-loginov/parcel-namer-rewrite)
- [parcel-plugin-structurize](https://github.com/samrith-s/parcel-plugin-structurize)

**Comment by VladimirMikulic** [comment]
Hi @iocouto. I appreciate your comment.
`parcel-namer-rewrite` is for Parcel version 2 while this one is for v1.

This plugin is maintained, no issues as you can see :)

**Comment by iocouto** [comment]
@VladimirMikulic indeed, you do a great job! :)
Would love to see this updated for Parcel 2, though. I thought maybe joining forces with other devs might motivate you, or make the job seem easier?... 😉

**Comment by VladimirMikulic** [comment]
Parcel 2 plugin architecture is quite simple so many developers have come up with their own solution.
I guess we'll have to see who will emerge as a winner :)

The situation is a bit different for Parcel 1 though since it has very complex structure which forced me to come up with my own solution since there were no other solutions at a time.

Parcel 2 is the future, this plugin is just for legacy projects.
We'll see who will be parcel-plugin-custom-dist-structure for v2 :)

**Comment by iocouto** [comment]
@VladimirMikulic so far the only one I've been able to find that targets v2 is [parcel-namer-rewrite](https://github.com/ol-loginov/parcel-namer-rewrite) - if you know others, please do share! Right now, not being able to setup custom distDirs in Parcel 2 is stopping me from being able to use it...

**Comment by VladimirMikulic** [comment]
Sure! There are plenty of them! Just search for [parcel-namer](https://www.npmjs.com/search?q=parcel-namer).

**Comment by VladimirMikulic** [comment]
@iocouto haha, I even forgot that I have my own.
If you want to try it, here it is: https://github.com/VladimirMikulic/parcel-resolver-ignore
