### ISSUE TITLE
Custom dist structure in parcel v2

### ISSUE THREAD

**Issue by astegmaier** [VladimirMikulic/parcel-plugin-custom-dist-structure#47]
Hi! I found this package through a [stackoverflow issue](https://stackoverflow.com/a/60684675/4739687) that you answered. Thanks for contributing your work to the community!

The readme says
> This is the plugin for Parcel v1. The plugin for the second version can be found [here](https://github.com/VladimirMikulic/parcel-resolver-ignore).

However, the link to the "second version", although it does support parcelv2, seems to have some pretty different functionality - ignoring assets, instead of re-structuring the folder output.

Someone else [asked a similar question](https://stackoverflow.com/questions/62900160/how-to-handle-output-files-in-parcel/69543953#69543953) more recently that I answered by providing some sample code on how to write a plugin similar to this one, but for v2.

I was thinking of starting a project that had the goal of matching the functionality of this plugin, but with support for v2, and I wanted to check with you to see if you had already started this work, or if you'd like to collaborate? It's okay if not - I'll just write it myself. But I thought it might be good to not duplicate work if possible, and to make sure the docs of both plugins reference each other so people have an easier time finding the right one.

**Comment by AndreaBaccolini** [comment]
> Hi! I found this package through a [stackoverflow issue](https://stackoverflow.com/a/60684675/4739687) that you answered. Thanks for contributing your work to the community!
> 
> The readme says
> 
> > This is the plugin for Parcel v1. The plugin for the second version can be found [here](https://github.com/VladimirMikulic/parcel-resolver-ignore).
> 
> However, the link to the "second version", although it does support parcelv2, seems to have some pretty different functionality - ignoring assets, instead of re-structuring the folder output.
> 
> Someone else [asked a similar question](https://stackoverflow.com/questions/62900160/how-to-handle-output-files-in-parcel/69543953#69543953) more recently that I answered by providing some sample code on how to write a plugin similar to this one, but for v2.
> 
> I was thinking of starting a project that had the goal of matching the functionality of this plugin, but with support for v2, and I wanted to check with you to see if you had already started this work, or if you'd like to collaborate? It's okay if not - I'll just write it myself. But I thought it might be good to not duplicate work if possible, and to make sure the docs of both plugins reference each other so people have an easier time finding the right one.

Hello @astegmaier. have you started working on version 2 of the plugin? I'd be interested . Thank you

**Comment by astegmaier** [comment]
Yes - I started [here](https://github.com/astegmaier/parcel-namer-custom-dist-structure). It seems to basically work, but I haven't had time recently to finish it - I want to think harder about the config API, add more unit tests, and publish it.

If you'd like to collaborate, feel free to submit a PR!

**Comment by teak** [comment]
Perhaps clarify that this repo is for Parcel 1. I know Parcel 2 is fairly new, but as a new Parcel user starting on v2, I have accidentally installed way too many plugins not knowing that they are for Parcel 1.
