### ISSUE TITLE
parcel localhost breaks when customDistStructure is added to package.json

### ISSUE THREAD

**Issue by maarten-mobron** [VladimirMikulic/parcel-plugin-custom-dist-structure#48]
**Describe the bug**
When a customDistStructure is added to package.json the localhost from parcel breaks.

A solution would be that its only uses the customDistStructure when npm run build is used and not with npm start. The problem is that i don't know how I can achieve that.

**How it happened?**
when trying to run npm start or npm run build.

**Desktop (please complete the following information):**
- OS: [Windows]
- Parcel version: [1.12.5]
- Plugin version: [1.1.19]

**Plugin configuration object:**
```
"customDistStructure": {
"config": {
".js": "scripts",
".js.map": "scripts",
".css": "styles",
".css.map": "styles",
".html": "pages",

"img": [
".jpg",
".png"
],
"video": [
".mp4",
".mov",
".avi",
".flv"
]

},
"options": {
"development": true
}
}
```

**Comment by VladimirMikulic** [comment]
Hello @maarten-mobron!
Setting development to `false` should resolve your issue.

Also, Parcel 2 stable has been released which is the future so I no longer maintain this one :)
