### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by HowardvanRooijen** [VladimirMikulic/parcel-plugin-custom-dist-structure#8]
Hi! Just giving the plugin a spin against a project I'm working on and I get the following error when I run with the plugin installed:

```
Server running at http://localhost:1234
√  Built in 20.18s.
×  Maximum call stack size exceeded
    at Map.entries (<anonymous>)
    at Function.from (<anonymous>)
    at DependencyGraph.buildDependencyAssets (C:\MyProject\Publish\node_modules\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:51:36)
    at C:\MyProject\Publish\node_modules\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:62:14
    at Array.forEach (<anonymous>)
    at DependencyGraph.buildDependencyAssets (C:\MyProject\Publish\node_modules\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:53:22)
    at C:\MyProject\Publish\node_modules\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:62:14
    at Array.forEach (<anonymous>)
    at DependencyGraph.buildDependencyAssets (C:\MyProject\Publish\node_modules\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:53:22)
    at C:\MyProject\Publish\node_modules\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:62:14
```

The project has around 800 html & image files.

**Comment by VladimirMikulic** [comment]
Hi @HowardvanRooijen. Thank you for reporting this issue.
Could you please post here your configuration object?

Also, if you don't mind, how are these 800 HTML files connected? Are they all dependencies of one single HTML file which then includes the rest (like a tree structure), or they are separate?

Thank you.

**Comment by HowardvanRooijen** [comment]
Hi,

I had got as far as using the default configuration from the readme.

The site is a port of our blog site - I've gone from WordPress to Markdown, then using a custom SSG to generate the new static site, then using parceljs to package / minify etc. That all works absolutely fine... I just gave your plugin a try, because all the images are dumped in the root of the site, and I quite wanted a bit more control - just because there is such a lot of content!

**Comment by VladimirMikulic** [comment]
Alright, great! This is going to be a bit tricky to debug since I don't have the whole dependency graph to inspect, but I'll try my best :)
Have you tried running a production build `parcel build <entries>`? Does the error occur there as well?

**Comment by HowardvanRooijen** [comment]
I'll give it a go. I might be able to provide you with a dump of the raw files, if that'll help?

**Comment by VladimirMikulic** [comment]
Any clue that I can get my hands on is helpful. Thank you :+1:

**Comment by VladimirMikulic** [comment]
@HowardvanRooijen I might not even need it.
I think I've fixed it, but I'll need your help to verify this :)

I would like you to test it, the steps are:
1. Clone the project: `git clone https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure.git`
2. Check out the test branch: `git checkout fix/build-dependency-assets-stack-overflow`
3. Make it available globally on your system: `npm link`
4. After running npm link, you'll get the absolute path to the package -> copy it
5. Enter your project and run npm i -D <absolute_path> to install the plugin (before this, make sure to delete the version from NPM)
6. Report the results here

Thank you.

**Comment by HowardvanRooijen** [comment]
Think I have it all set up OK, but still getting:

```
×  Maximum call stack size exceeded
    at DependencyGraph.addNode (C:\_Projects\OSS\parcel-plugin-custom-dist-structure\node_modules\dependency-graph\lib\dep_graph.js:1:1)
    at C:\_Projects\OSS\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:59:12
    at Array.forEach (<anonymous>)
    at DependencyGraph.buildDepAssets (C:\_Projects\OSS\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:55:22)
    at C:\_Projects\OSS\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:64:14
    at Array.forEach (<anonymous>)
    at DependencyGraph.buildDepAssets (C:\_Projects\OSS\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:55:22)
    at C:\_Projects\OSS\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:64:14
    at Array.forEach (<anonymous>)
    at DependencyGraph.buildDepAssets (C:\_Projects\OSS\parcel-plugin-custom-dist-structure\lib\DependencyGraph.js:55:22)
```

**Comment by VladimirMikulic** [comment]
So far so good. At least I've eliminated one option.
I've updated the branch, could you please follow the step again and see if this fixed the issue?

Thank you.

**Comment by HowardvanRooijen** [comment]
W00t! That seems to have worked! Thanks very much. I'll enable it while I'm continuing to develop and see if it's stable... or if I can find any edge cases.

**Comment by VladimirMikulic** [comment]
That's awesome to hear. I'll leave the issue and PR open for 2 more days to be sure that this does work flawlessly on bigger projects and after that, I'll merge the PR and publish a new version to NPM.

**Comment by HowardvanRooijen** [comment]
Hi,

something odd is going on... I'm using the following configuration:

```
 "customDistStructure": {
    "config": {
      ".css": "assets/css", 
      "assets/js": [
        ".js",
        ".map"
      ],
      "assets/images": [
        ".gif",
        ".jpg",
        ".jpeg",
        ".png",
        ".svg"
      ],
       "assets/fonts": [
        ".woff",
        ".woff2"
      ]
    },
    "options": {
      "development": true
    }
```

The build runs, although I've been getting a lot of crashes today. I put that down to the fact I'm doing to work to deal with all the internal links... but since a reboot today, the build succeeds, but all the files are still in the root dist directory, then over the next 30 seconds the files seem to get copied to the destination directories as specified... it's quite slow and takes a while... the other side effect is that the webserver seems to hang - I've not been able to preview on :1234 - on the next one the port is locked and I get another randomly generated, but that doesn't serve content either...

**Comment by VladimirMikulic** [comment]
Hi @HowardvanRooijen.
The "issue" that you've described is how plugin actually works.
**After** the Parcel generates the build, **my plugin runs** and places the files in corresponding folders while also linking files accordingly.

You might be asking, "Why doesn't it place files at runtime, wouldn't it be faster?".
That's correct, it would be a 100 times faster, but Parcel's v1 architecture prevents me from doing it.
On sm-mid size projects, this is not a huge overhead(1-3sec), but on bigger projects like yours, the first build can take a while (1-2min maybe).
After it caches the first build, the following rebuilds(and file placements) are relatively fast, so you shouldn't have any problems in the development after the first build.

Parcel 2 will allow placing files at runtime, but it's not stable yet.
Once it gets to the stable version I'll make the plugin like this to cover the v2.
In v1, this is how the things work :)

**Comment by HowardvanRooijen** [comment]
Thanks! That makes sense. Would it impact the web server being able to serve content?

**Comment by VladimirMikulic** [comment]
Parcel's development server is not meant to be used as a production server, if that's what you had in mind.

**Comment by VladimirMikulic** [comment]
v1.1.5 has been released! Thank you for your help.
Now, the plugin is ready for enterprise projects 😎
